import mongoose from 'mongoose';
import FinanceStockMovement from '../models/financeStockMovement.js';
import { broadcast } from '../middlewares/webSocket.js';

const MANUAL_TYPES = ['dump', 'return', 'waste'];

const listStockMovements = async (req, res) => {
    try {
        const { projectId, materialId, movementType } = req.query;
        if (!projectId) return res.status(400).json({ success: false, message: 'projectId is required' });
        const filter = { projectId, deleted: { $ne: true } };
        if (materialId) filter.materialId = materialId;
        if (movementType) filter.movementType = movementType;
        const items = await FinanceStockMovement.find(filter)
            .populate('materialId', 'name unit')
            .sort({ date: -1, createdAt: -1 });
        res.json({ success: true, data: items });
    } catch (err) {
        console.error(err);
        res.status(500).json({ success: false, message: 'Error fetching stock movements' });
    }
};

// `consume` movements are only ever created by the measurement-save
// automation (controllers/financeMeasurement.js) — rejected here so the
// stock ledger can't drift out of sync with what was actually measured.
const addStockMovement = async (req, res) => {
    try {
        const { projectId, materialId, movementType, quantity, date, notes } = req.body;
        if (!projectId || !materialId || !movementType || !date) {
            return res.status(400).json({ success: false, message: 'Project, material, movement type, and date are required' });
        }
        if (!MANUAL_TYPES.includes(movementType)) {
            return res.status(400).json({ success: false, message: 'movementType must be dump, return, or waste — consume movements are created automatically from measurements' });
        }
        if (!quantity || Number(quantity) <= 0) {
            return res.status(400).json({ success: false, message: 'Quantity must be greater than zero' });
        }
        const item = new FinanceStockMovement({
            projectId, materialId, movementType, quantity: Number(quantity), date, notes: notes || '',
        });
        await item.save();
        broadcast({ type: 'financeStockChanged', projectId });
        res.json({ success: true, message: 'Stock movement recorded', data: item });
    } catch (err) {
        console.error(err);
        res.status(500).json({ success: false, message: 'Error adding stock movement' });
    }
};

const removeStockMovement = async (req, res) => {
    try {
        const { _id } = req.body;
        const item = await FinanceStockMovement.findById(_id);
        if (!item) return res.status(404).json({ success: false, message: 'Not found' });
        if (item.relatedMeasurementId) {
            return res.status(400).json({ success: false, message: 'This movement was generated by a measurement — remove the measurement instead' });
        }
        item.deleted = true; item.deletedAt = new Date(); item.deletedBy = req.userName || 'Admin';
        await item.save();
        broadcast({ type: 'financeStockChanged', projectId: item.projectId });
        res.json({ success: true, message: 'Stock movement removed' });
    } catch (err) {
        console.error(err);
        res.status(500).json({ success: false, message: 'Error removing stock movement' });
    }
};

// Current stock is never stored — always SUM(dump) − SUM(consume) −
// SUM(return) − SUM(waste), grouped by (projectId, materialId), computed
// fresh on every call.
const getCurrentStock = async (req, res) => {
    try {
        const { projectId, materialId } = req.query;
        if (!projectId) return res.status(400).json({ success: false, message: 'projectId is required' });

        const match = { projectId: new mongoose.Types.ObjectId(projectId), deleted: { $ne: true } };
        if (materialId) match.materialId = new mongoose.Types.ObjectId(materialId);

        const rows = await FinanceStockMovement.aggregate([
            { $match: match },
            {
                $group: {
                    _id: '$materialId',
                    dump:    { $sum: { $cond: [{ $eq: ['$movementType', 'dump'] }, '$quantity', 0] } },
                    consume: { $sum: { $cond: [{ $eq: ['$movementType', 'consume'] }, '$quantity', 0] } },
                    returned: { $sum: { $cond: [{ $eq: ['$movementType', 'return'] }, '$quantity', 0] } },
                    waste:   { $sum: { $cond: [{ $eq: ['$movementType', 'waste'] }, '$quantity', 0] } },
                },
            },
            {
                $lookup: { from: 'financematerials', localField: '_id', foreignField: '_id', as: 'material' },
            },
            { $unwind: { path: '$material', preserveNullAndEmptyArrays: true } },
            {
                $project: {
                    _id: 0,
                    materialId: '$_id',
                    materialName: '$material.name',
                    unit: '$material.unit',
                    dump: 1, consume: 1, returned: 1, waste: 1,
                    currentStock: { $subtract: [{ $subtract: [{ $subtract: ['$dump', '$consume'] }, '$returned'] }, '$waste'] },
                },
            },
            { $sort: { materialName: 1 } },
        ]);

        res.json({ success: true, data: rows });
    } catch (err) {
        console.error(err);
        res.status(500).json({ success: false, message: 'Error computing current stock' });
    }
};

export { listStockMovements, addStockMovement, removeStockMovement, getCurrentStock };
