import FinanceCashEntry from '../models/financeCashEntry.js';
import { broadcast } from '../middlewares/webSocket.js';

const listCashEntries = async (req, res) => {
    try {
        const { projectId, dateFrom, dateTo } = req.query;
        const filter = { deleted: { $ne: true } };
        if (projectId) filter.projectId = projectId;
        if (dateFrom || dateTo) {
            filter.date = {};
            if (dateFrom) filter.date.$gte = new Date(dateFrom);
            if (dateTo) filter.date.$lte = new Date(dateTo);
        }
        const items = await FinanceCashEntry.find(filter).sort({ date: -1, createdAt: -1 });
        res.json({ success: true, data: items });
    } catch (err) {
        console.error(err);
        res.status(500).json({ success: false, message: 'Error fetching cash entries' });
    }
};

// Manual entries only — for cash with no originating record (petty cash,
// owner draws). None of the relatedXId fields are ever accepted here, even
// if present in the request body; they're only ever set by the
// receipt/contractor-payment/vendor-payment/salary-payment/commission-
// payment/expense automation.
const addCashEntry = async (req, res) => {
    try {
        const { date, type, amount, projectId, reason, notes } = req.body;
        if (!['in', 'out'].includes(type)) return res.status(400).json({ success: false, message: 'type must be in or out' });
        if (!amount || Number(amount) <= 0) return res.status(400).json({ success: false, message: 'Amount must be greater than zero' });
        if (!reason || !reason.trim()) return res.status(400).json({ success: false, message: 'Reason is required' });
        if (!date) return res.status(400).json({ success: false, message: 'Date is required' });

        const item = new FinanceCashEntry({
            date, type, amount: Number(amount), projectId: projectId || null, reason: reason.trim(), notes: notes || '',
        });
        await item.save();
        broadcast({ type: 'financeCashBookChanged' });
        res.json({ success: true, message: 'Cash entry recorded', data: item });
    } catch (err) {
        console.error(err);
        res.status(500).json({ success: false, message: 'Error recording cash entry' });
    }
};

const removeCashEntry = async (req, res) => {
    try {
        const { _id } = req.body;
        const item = await FinanceCashEntry.findById(_id);
        if (!item) return res.status(404).json({ success: false, message: 'Not found' });
        const isAutoGenerated = item.relatedReceiptId || item.relatedContractorPaymentId || item.relatedVendorPaymentId
            || item.relatedSalaryPaymentId || item.relatedCommissionPaymentId || item.relatedExpenseId
            || item.relatedDailyLabourId || item.relatedSupervisorIncentiveId
            || item.relatedSupervisorLabourPaymentId || item.relatedExpensePaymentId;
        if (isAutoGenerated) {
            return res.status(400).json({ success: false, message: 'This entry was generated by a receipt/payment/expense — remove that instead' });
        }
        item.deleted = true; item.deletedAt = new Date(); item.deletedBy = req.userName || 'Admin';
        await item.save();
        broadcast({ type: 'financeCashBookChanged' });
        res.json({ success: true, message: 'Cash entry removed' });
    } catch (err) {
        console.error(err);
        res.status(500).json({ success: false, message: 'Error removing cash entry' });
    }
};

export { listCashEntries, addCashEntry, removeCashEntry };
