import React, { useState } from 'react';
import FinanceTabShell from '../../components/finance/FinanceTabShell';
import CashEntriesManager from '../../components/finance/CashEntriesManager';
import CashBookSummaryView from '../../components/finance/CashBookSummaryView';

const TABS = [
    { key: 'cash-in',  label: 'Cash In' },
    { key: 'cash-out', label: 'Cash Out' },
    { key: 'opening-closing', label: 'Opening / Closing' },
];

const CashBookPage = ({ url }) => {
    const [activeTab, setActiveTab] = useState(TABS[0].key);

    return (
        <FinanceTabShell
            label="Cash Book"
            subtitle="Cash in, cash out, and opening/closing balance by date range. Entries generated by a cash-mode receipt or payment are read-only here — edit the originating record instead."
            tabs={TABS}
            activeKey={activeTab}
            onTabChange={setActiveTab}
        >
            {activeTab === 'cash-in' && <CashEntriesManager url={url} type="in" />}
            {activeTab === 'cash-out' && <CashEntriesManager url={url} type="out" />}
            {activeTab === 'opening-closing' && <CashBookSummaryView url={url} />}
        </FinanceTabShell>
    );
};

export default CashBookPage;
