import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { toast } from 'react-toastify';
import StyledSelect from './StyledSelect';
import '../../styles/list.css';
import '../../styles/dashboard.css';

/* Read-only — dump-type stock movements generated by Procurement purchases
   specifically (relatedPurchaseId set), viewed through the inventory lens
   rather than the purchase lens. Distinct from Site Inventory's own dump
   view, which shows every dump movement including manually-entered
   opening stock (no relatedPurchaseId). */
const MaterialDumpView = ({ url }) => {
    const token = localStorage.getItem('token');
    const authHeader = { headers: { Authorization: `Bearer ${token}` } };
    const [projects, setProjects] = useState([]);
    const [projectsLoading, setProjectsLoading] = useState(true);
    const [selectedProjectId, setSelectedProjectId] = useState('');
    const [movements, setMovements] = useState([]);
    const [loading, setLoading] = useState(false);

    useEffect(() => {
        axios.get(`${url}/api/finance/projects/list`, authHeader).then(res => { if (res.data.success) setProjects(res.data.data); }).catch(() => {}).finally(() => setProjectsLoading(false));
    }, [url]); // eslint-disable-line react-hooks/exhaustive-deps

    useEffect(() => {
        if (!selectedProjectId) { setMovements([]); return; }
        setLoading(true);
        axios.get(`${url}/api/finance/stock-movements/list`, { ...authHeader, params: { projectId: selectedProjectId, movementType: 'dump' } })
            .then(res => { if (res.data.success) setMovements(res.data.data.filter(m => m.relatedPurchaseId)); })
            .catch(() => toast.error('Error fetching material dump'))
            .finally(() => setLoading(false));
    }, [url, selectedProjectId]); // eslint-disable-line react-hooks/exhaustive-deps

    return (
        <div>
            <div className="add-product-name flex-col" style={{ marginBottom: '20px', maxWidth: '360px' }}>
                <p>Project</p>
                <StyledSelect value={selectedProjectId} onChange={setSelectedProjectId} placeholder="Select project…" loading={projectsLoading}
                    options={projects.map(p => ({ value: p._id, label: p.name }))} />
            </div>

            {!selectedProjectId ? (
                <div className="admin-empty-state"><p>Select a project to view its purchase-generated material dump.</p></div>
            ) : (
                loading ? (
                    <div className="admin-empty-state"><p>Loading…</p></div>
                ) : movements.length === 0 ? (
                    <div className="admin-empty-state"><p>No purchase-generated dumps yet; this fills in as purchases are recorded.</p></div>
                ) : (
                    <div className="dash-chart-card md-card">
                        <div className="md-row md-header">
                            <b className="md-date">Date</b>
                            <b className="md-material">Material</b>
                            <b className="md-qty">Quantity</b>
                        </div>
                        {movements.map(m => (
                            <div key={m._id} className="md-row">
                                <p className="md-date"><span className="pq-group-label">Date</span>{new Date(m.date).toLocaleDateString()}</p>
                                <p className="md-material">{m.materialId?.name || '-'}</p>
                                <p className="md-qty"><span className="pq-group-label">Quantity</span>{m.quantity} {m.materialId?.unit || ''}</p>
                            </div>
                        ))}
                    </div>
                )
            )}
        </div>
    );
};

export default MaterialDumpView;
